{
 "title": "Cosmos Validator Watcher By Chain",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cosmos_validator_watcher_block_height,chain_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All Chains",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validators Stats",
     "type": "table",
     "gridPos": { "h": 21, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "100 * \nsum(rate(cosmos_validator_watcher_validated_blocks[5m])) by (chain_id, name) \n/ on(instance, chain_id) group_left() \nsum(rate(cosmos_validator_watcher_tracked_blocks[5m])) by (chain_id)"
      },
      {
       "expr": "100 * \nsum(rate(cosmos_validator_watcher_solo_missed_blocks[5m])) by (chain_id, name) \n/ on(instance, chain_id) group_left() \nsum(rate(cosmos_validator_watcher_tracked_blocks[5m])) by (chain_id)"
      },
      {
       "expr": "max(cosmos_validator_watcher_empty_blocks{chain_id=\"$chain_id\"}) by (name)"
      },
      {
       "expr": "100 * (sum(rate(cosmos_validator_watcher_validated_blocks{chain_id=\"$chain_id\"}[5m])) by (name) - sum(rate(cosmos_validator_watcher_empty_blocks{chain_id=\"$chain_id\"}[5m])) by (name)) / sum(rate(cosmos_validator_watcher_validated_blocks{chain_id=\"$chain_id\"}[5m])) by (name)"
      },
      {
       "expr": "max(cosmos_validator_watcher_rank) by (name)"
      },
      {
       "expr": "max(cosmos_validator_watcher_tokens) by (name)"
      },
      {
       "expr": "max(cosmos_validator_watcher_is_bonded) by (name)"
      },
      {
       "expr": "max(cosmos_validator_watcher_is_jailed) by (name)"
      }
     ]
    },
    {
     "title": "Votes",
     "type": "table",
     "gridPos": { "h": 21, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "min(cosmos_validator_watcher_vote) by (namespace, chain_id, name, proposal_id)"
      }
     ]
    }
   ]
  },
  { "title": "Global Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"})"
    }
   ]
  },
  {
   "title": "Block / min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(increase(cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"}[10m])) by (chain_id) / 10"
    }
   ]
  },
  {
   "title": "Active Set",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validator_watcher_active_set{chain_id=\"$chain_id\"})"
    }
   ]
  },
  {
   "title": "Total Staked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validator_watcher_tokens{chain_id=\"$chain_id\"})"
    }
   ]
  },
  {
   "title": "Seat Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validator_watcher_seat_price{chain_id=\"$chain_id\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Next Upgrade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validator_watcher_upgrade_plan{chain_id=\"$chain_id\"}) by (chain_id)"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cosmos_validator_watcher_upgrade_plan{chain_id=\"$chain_id\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Estimated Date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*\n(time() +\n(\n    max(cosmos_validator_watcher_upgrade_plan{chain_id=\"$chain_id\"}) by (chain_id) - \n    max(cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"}) by (chain_id)\n) \n/\nsum(predict_linear(cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"}[5h], 5*60) - cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"}) by (chain_id) \n* 5*60)"
    }
   ]
  },
  {
   "title": "Remaining Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    max(cosmos_validator_watcher_upgrade_plan{chain_id=\"$chain_id\"}) by (chain_id) - \n    max(cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"}) by (chain_id)\n) \n/\nsum(predict_linear(cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"}[10h], 10*60) - cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"}) by (chain_id) \n* 10*60"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Validators Stats",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "100 * \nsum(rate(cosmos_validator_watcher_validated_blocks{chain_id=\"$chain_id\"}[5m])) by (name)\n/ on(instance) group_left()\nsum(rate(cosmos_validator_watcher_tracked_blocks{chain_id=\"$chain_id\"}[5m]))"
    },
    {
     "expr": "100 * \nsum(rate(cosmos_validator_watcher_solo_missed_blocks{chain_id=\"$chain_id\"}[5m])) by (name)\n/ on(instance) group_left()\nsum(rate(cosmos_validator_watcher_tracked_blocks{chain_id=\"$chain_id\"}[5m]))"
    },
    {
     "expr": "max(cosmos_validator_watcher_rank{cluster=\"$cluster\",namespace=\"$namespace\"}) by (name)"
    },
    {
     "expr": "max(cosmos_validator_watcher_tokens{chain_id=\"$chain_id\"}) by (name)"
    },
    {
     "expr": "max(cosmos_validator_watcher_is_bonded{chain_id=\"$chain_id\"}) by (name)"
    },
    {
     "expr": "max(cosmos_validator_watcher_is_jailed{chain_id=\"$chain_id\"}) by (name)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 36, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{job=\"cosmoslog\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "100 * \nsum(rate(cosmos_validator_watcher_validated_blocks{chain_id=\"$chain_id\"}[5m])) by (name)\n/ on(instance) group_left()\nsum(rate(cosmos_validator_watcher_tracked_blocks{chain_id=\"$chain_id\"}[5m]))"
    }
   ]
  },
  {
   "title": "Missed Blocks (Solo)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max(increase(cosmos_validator_watcher_solo_missed_blocks{chain_id=\"$chain_id\"}[30s])) by (name)"
    }
   ]
  },
  {
   "title": "Block / min",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "max(increase(cosmos_validator_watcher_block_height{chain_id=\"$chain_id\"}[10m])) by (chain_id) / 10"
    }
   ]
  },
  {
   "title": "Nodes Sync",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max(cosmos_validator_watcher_node_synced{chain_id=\"$chain_id\"}) by (node)"
    },
    {
     "expr": "max(increase(cosmos_validator_watcher_node_block_height{chain_id=\"$chain_id\"}[5m])) by (node) / 5"
    }
   ]
  },
  {
   "title": "Votes",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "min(cosmos_validator_watcher_vote{chain_id=\"$chain_id\"}) by (name, proposal_id)"
    }
   ]
  }
 ]
}